"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
  { on = [
    "l",
  ], run = "plugin smart-enter" },
  { on = [
    "<C-s>",
  ], run = '''shell "$SHELL" --block --confirm''' },
  { on = [
    "<C-g>",
  ], run = "shell lazygit --block --confirm" },
  { on = [
    "g",
    "l",
  ], run = "cd ~/.local", desc = "Go ~/.local" },
  { on = [
    "g",
    "w",
  ], run = "cd ~/workspace", desc = "Go ~/workspace" },
]
