;;; aklk1ng-theme.el --- Aklk1ng color theme -*- lexical-binding: t; -*-

;; https://github.com/vedang/alabaster-themes

(deftheme aklk1ng)

(let ((aklk1ng-bg          "#0E1415")
      (aklk1ng-bg-1        "#121818")
      (aklk1ng-bg+1        "#1a1a1a")
      (aklk1ng-bg+2        "#1f2526")
      (aklk1ng-bg+3        "#293334")
      (aklk1ng-bg+4        "#202633")
      (aklk1ng-fg          "#CECECE")
      (aklk1ng-fg+1        "#a0a0a0")
      (aklk1ng-fg+2        "#ffffff")
      (aklk1ng-fg-1        "#666666")
      (aklk1ng-fg-2        "#888888")
      (aklk1ng-border      "#444444")
      (aklk1ng-blue        "#8AB1F0")
      (aklk1ng-green       "#95CB82")
      (aklk1ng-yellow      "#DFDF8E")
      (aklk1ng-magenta     "#CC8BC9")
      (aklk1ng-orange      "#CD974B")
      (aklk1ng-red         "#ff6b6b")
      (aklk1ng-error-bg    "#332020")
      (aklk1ng-diff-add-bg "#1f3a1f")
      (aklk1ng-diff-chg-bg "#3a2f1f")
      (aklk1ng-diff-del-bg "#3a1f1f")
      (aklk1ng-diff-add-bg+ "#0f2f0f")
      (aklk1ng-diff-chg-bg+ "#2f2f0f")
      (aklk1ng-diff-del-bg+ "#2f0f0f")
      (aklk1ng-diff-add-bg "#2a4a2a")
      (aklk1ng-diff-chg-bg "#4a3f2a")
      (aklk1ng-diff-del-bg "#4a2a2a"))

  (custom-theme-set-faces
   'aklk1ng

   ;; ── Basic ──────────────────────────────────────────────
   `(default ((t (:background ,aklk1ng-bg :foreground ,aklk1ng-fg))))
   `(cursor ((t (:background ,aklk1ng-fg+2))))
   `(minibuffer-prompt ((t (:foreground ,aklk1ng-blue))))
   `(highlight ((t (:background ,aklk1ng-bg+3 :foreground ,aklk1ng-fg+2))))
   `(region ((t (:background ,aklk1ng-bg+3 :foreground ,aklk1ng-fg))))
   `(shadow ((t (:foreground ,aklk1ng-fg-1))))
   `(secondary-selection ((t (:foreground ,aklk1ng-bg+3))))
   `(trailing-whitespace ((t (:background ,aklk1ng-red))))

   ;; ── Font Lock ──────────────────────────────────────────
   `(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
   `(font-lock-builtin-face ((t (:foreground ,aklk1ng-yellow))))
   `(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
   `(font-lock-comment-face ((t (:foreground ,aklk1ng-yellow))))
   `(font-lock-constant-face ((t (:foreground ,aklk1ng-magenta))))
   `(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
   `(font-lock-doc-face ((t (:inherit font-lock-string-face))))
   `(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
   `(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
   `(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
   `(font-lock-function-name-face ((t (:foreground ,aklk1ng-blue))))
   `(font-lock-keyword-face ((t (:foreground ,aklk1ng-fg))))
   `(font-lock-negation-char-face ((t nil)))
   `(font-lock-number-face ((t nil)))
   `(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
   `(font-lock-operator-face ((t nil)))
   `(font-lock-preprocessor-face ((t (:foreground ,aklk1ng-magenta))))
   `(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
   `(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
   `(font-lock-punctuation-face ((t nil)))
   `(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
   `(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
   `(font-lock-string-face ((t (:foreground ,aklk1ng-green))))
   `(font-lock-type-face ((t (:foreground ,aklk1ng-fg))))
   `(font-lock-variable-name-face ((t nil)))
   `(font-lock-variable-use-face ((t nil)))
   `(font-lock-warning-face ((t (:inherit warning))))

   ;; ── Links / Buttons ────────────────────────────────────
   `(button ((t (:foreground ,aklk1ng-blue :underline ,aklk1ng-border))))
   `(link ((t (:foreground ,aklk1ng-blue :underline ,aklk1ng-border))))
   `(link-visited ((t (:foreground unspecified :underline ,aklk1ng-border))))
   `(custom-link ((t (:inherit link))))

   ;; ── Fringe / Mode-line / Tab ─────────────────────────────────
   `(fringe ((t (:foreground ,aklk1ng-fg-1))))
   `(header-line ((t (:inherit mode-line))))
   `(tooltip ((t (:background ,aklk1ng-bg+2 :foreground ,aklk1ng-fg+2))))
   `(mode-line ((t (:background ,aklk1ng-bg+2 :foreground ,aklk1ng-fg))))
   `(mode-line-buffer-id ((t (:inherit bold))))
   `(mode-line-emphasis ((t (:inherit bold))))
   `(mode-line-highlight ((t (:inherit highlight))))
   `(mode-line-inactive ((t (:background ,aklk1ng-bg-1 :foreground ,aklk1ng-fg-1))))
   `(tab-bar ((t (:background ,aklk1ng-bg))))
   `(tab-bar-tab ((t (:background ,aklk1ng-bg))))

   ;; ── Search / Highlight ─────────────────────────────────
   `(isearch ((t (:background ,aklk1ng-orange :foreground ,aklk1ng-fg+2))))
   `(isearch-fail ((t (:foreground ,aklk1ng-fg :background ,aklk1ng-red))))
   `(lazy-highlight ((t (:background ,aklk1ng-border))))
   `(match ((t (:background ,aklk1ng-bg+4))))
   `(next-error ((t (:inherit (region)))))
   `(query-replace ((t (:inherit (isearch)))))

   ;; ── Line numbers / Current line ────────────────────────
   `(line-number ((t (:foreground ,aklk1ng-fg-1))))
   `(line-number-current-line ((t (:foreground ,aklk1ng-fg+2))))
   `(hl-line ((t (:background ,aklk1ng-bg+1))))

   ;; ── Semantic states ────────────────────────────────────
   `(error ((t (:inherit bold :foreground ,aklk1ng-red))))
   `(warning ((t (:inherit bold :foreground ,aklk1ng-orange))))
   `(success ((t (:inherit bold :foreground ,aklk1ng-green))))

   ;; ── Diff ───────────────────────────────────────────────
   `(diff-added ((t (:background ,aklk1ng-diff-add-bg :foreground ,aklk1ng-green))))
   `(diff-changed ((t (:background ,aklk1ng-diff-chg-bg :foreground ,aklk1ng-orange))))
   `(diff-removed ((t (:background ,aklk1ng-diff-del-bg :foreground ,aklk1ng-red))))
   `(diff-header ((t (:inherit bold))))
   `(diff-file-header ((t (:inherit bold :background ,aklk1ng-bg+2))))
   `(diff-hunk-header ((t (:background ,aklk1ng-bg+3 :foreground ,aklk1ng-fg+2))))
   `(diff-context ((t (:foreground ,aklk1ng-fg-2))))
   `(diff-indicator-added ((t (:inherit diff-added))))
   `(diff-indicator-changed ((t (:inherit diff-changed))))
   `(diff-indicator-removed ((t (:inherit diff-removed))))
   `(diff-refine-added ((t (:background ,aklk1ng-diff-add-bg+ :foreground ,aklk1ng-green))))
   `(diff-refine-changed ((t (:background ,aklk1ng-diff-chg-bg+ :foreground ,aklk1ng-orange))))
   `(diff-refine-removed ((t (:background ,aklk1ng-diff-del-bg+ :foreground ,aklk1ng-red))))

   ;; ── Helper faces ─────────────────────────────
   `(aklk1ng-themes-heading-0 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(aklk1ng-themes-heading-1 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(aklk1ng-themes-heading-2 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(aklk1ng-themes-heading-3 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(aklk1ng-themes-heading-4 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(aklk1ng-themes-heading-5 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(aklk1ng-themes-heading-6 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(aklk1ng-themes-heading-7 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(aklk1ng-themes-heading-8 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(aklk1ng-themes-mark-delete ((t (:inherit error :background ,aklk1ng-error-bg))))
   `(aklk1ng-themes-mark-select ((t (:foreground ,aklk1ng-magenta))))
   `(aklk1ng-themes-mark-other ((t (:inherit warning))))
   `(aklk1ng-themes-search-current ((t (:background ,aklk1ng-orange :foreground ,aklk1ng-fg+2))))
   `(aklk1ng-themes-search-replace ((t (:background ,aklk1ng-error-bg :foreground ,aklk1ng-fg+2))))
   `(aklk1ng-themes-search-rx-group-0 ((t (:background ,aklk1ng-bg+2 :foreground ,aklk1ng-fg+2))))
   `(aklk1ng-themes-search-rx-group-1 ((t (:background ,aklk1ng-error-bg :foreground ,aklk1ng-fg+2))))
   `(aklk1ng-themes-search-rx-group-2 ((t (:background ,aklk1ng-bg+2 :foreground ,aklk1ng-fg+2))))
   `(aklk1ng-themes-search-rx-group-3 ((t (:background ,aklk1ng-bg+4 :foreground ,aklk1ng-fg+2))))
   `(aklk1ng-themes-search-match ((t (:background ,aklk1ng-bg+4))))
   `(aklk1ng-themes-underline-error ((t (:underline (:style wave :color ,aklk1ng-red)))))
   `(aklk1ng-themes-underline-info ((t (:underline (:style wave :color ,aklk1ng-blue)))))
   `(aklk1ng-themes-underline-warning ((t (:underline (:style wave :color ,aklk1ng-orange)))))

   ;; ── Magit ──────────────────────────────────────────────
   `(magit-bisect-bad ((t (:inherit error))))
   `(magit-bisect-good ((t (:inherit success))))
   `(magit-bisect-skip ((t (:inherit warning))))
   `(magit-blame-dimmed ((t (:inherit shadow))))
   `(magit-blame-highlight ((t (:background ,aklk1ng-bg+3 :foreground ,aklk1ng-fg+2))))
   `(magit-branch-local ((t (:foreground ,aklk1ng-blue))))
   `(magit-branch-remote ((t (:foreground ,aklk1ng-magenta))))
   `(magit-branch-upstream ((t (:inherit italic))))
   `(magit-branch-warning ((t (:inherit warning))))
   `(magit-cherry-equivalent ((t (:foreground ,aklk1ng-magenta))))
   `(magit-cherry-unmatched ((t (:foreground ,aklk1ng-blue))))
   `(magit-diff-added ((t (:background ,aklk1ng-diff-add-bg :foreground ,aklk1ng-green))))
   `(magit-diff-added-highlight ((t (:background ,aklk1ng-diff-add-bg :foreground ,aklk1ng-green))))
   `(magit-diff-base ((t (:background ,aklk1ng-diff-chg-bg :foreground ,aklk1ng-orange))))
   `(magit-diff-base-highlight ((t (:background ,aklk1ng-diff-chg-bg :foreground ,aklk1ng-orange))))
   `(magit-diff-context ((t (:inherit shadow))))
   `(magit-diff-context-highlight ((t (:background ,aklk1ng-bg+1))))
   `(magit-diff-file-heading ((t (:inherit bold :foreground ,aklk1ng-blue))))
   `(magit-diff-file-heading-highlight ((t (:inherit magit-diff-file-heading :background ,aklk1ng-bg+2))))
   `(magit-diff-file-heading-selection ((t (:inherit bold :background ,aklk1ng-bg+3 :foreground ,aklk1ng-fg+2))))
   `(magit-diff-hunk-heading ((t (:background ,aklk1ng-bg+2))))
   `(magit-diff-hunk-heading-highlight ((t (:inherit bold :background ,aklk1ng-bg+3 :foreground ,aklk1ng-fg+2))))
   `(magit-diff-hunk-heading-selection ((t (:inherit bold :background ,aklk1ng-bg+3 :foreground ,aklk1ng-fg+2))))
   `(magit-diff-hunk-region ((t (:inherit bold))))
   `(magit-diff-removed ((t (:background ,aklk1ng-diff-del-bg :foreground ,aklk1ng-red))))
   `(magit-diff-removed-highlight ((t (:background ,aklk1ng-diff-del-bg :foreground ,aklk1ng-red))))
   `(magit-diff-whitespace-warning ((t (:inherit warning))))
   `(magit-dimmed ((t (:inherit shadow))))
   `(magit-hash ((t (:foreground ,aklk1ng-fg-2))))
   `(magit-head ((t (:foreground ,aklk1ng-blue))))
   `(magit-header-line ((t (:inherit bold :background ,aklk1ng-bg+2))))
   `(magit-log-author ((t (:foreground ,aklk1ng-fg+1))))
   `(magit-log-date ((t (:foreground ,aklk1ng-fg-2))))
   `(magit-log-graph ((t (:foreground ,aklk1ng-border))))
   `(magit-popup-argument ((t (:inherit bold :foreground ,aklk1ng-orange))))
   `(magit-popup-disabled-argument ((t (:inherit shadow))))
   `(magit-popup-heading ((t (:inherit bold :foreground ,aklk1ng-blue))))
   `(magit-popup-key ((t (:foreground ,aklk1ng-yellow))))
   `(magit-popup-option-value ((t (:foreground ,aklk1ng-magenta))))
   `(magit-process-ng ((t (:inherit error))))
   `(magit-process-ok ((t (:inherit success))))
   `(magit-reflog-amend ((t (:foreground ,aklk1ng-magenta))))
   `(magit-reflog-checkout ((t (:foreground ,aklk1ng-blue))))
   `(magit-reflog-cherry-pick ((t (:foreground ,aklk1ng-green))))
   `(magit-reflog-commit ((t (:foreground ,aklk1ng-green))))
   `(magit-reflog-merge ((t (:foreground ,aklk1ng-green))))
   `(magit-reflog-other ((t (:foreground ,aklk1ng-magenta))))
   `(magit-reflog-rebase ((t (:foreground ,aklk1ng-magenta))))
   `(magit-reflog-remote ((t (:foreground ,aklk1ng-blue))))
   `(magit-reflog-reset ((t (:inherit error))))
   `(magit-refname ((t (:foreground ,aklk1ng-fg-2))))
   `(magit-section-heading ((t (:inherit bold :foreground ,aklk1ng-blue))))
   `(magit-section-heading-selection ((t (:inherit bold :background ,aklk1ng-bg+3 :foreground ,aklk1ng-fg+2))))
   `(magit-section-highlight ((t (:background ,aklk1ng-bg+2))))
   `(magit-sequence-drop ((t (:foreground ,aklk1ng-fg-2))))
   `(magit-sequence-head ((t (:foreground ,aklk1ng-blue))))
   `(magit-sequence-part ((t (:foreground ,aklk1ng-orange))))
   `(magit-sequence-stop ((t (:foreground ,aklk1ng-green))))
   `(magit-signature-bad ((t (:inherit error))))
   `(magit-signature-error ((t (:inherit error))))
   `(magit-signature-expired ((t (:inherit warning))))
   `(magit-signature-good ((t (:inherit success))))
   `(magit-signature-revoked ((t (:inherit warning))))
   `(magit-signature-untrusted ((t (:inherit warning))))
   `(magit-tag ((t (:foreground ,aklk1ng-magenta))))

   ;; ── Org ────────────────────────────────────────────────
   `(org-agenda-calendar-daterange ((t (:foreground ,aklk1ng-fg+1))))
   `(org-agenda-calendar-event ((t (:foreground ,aklk1ng-fg))))
   `(org-agenda-calendar-sexp ((t (:inherit (italic org-agenda-calendar-event)))))
   `(org-agenda-clocking ((t (:foreground ,aklk1ng-orange))))
   `(org-agenda-column-dateline ((t (:background ,aklk1ng-bg+2))))
   `(org-agenda-current-time ((t (:foreground ,aklk1ng-fg+2))))
   `(org-agenda-date ((t (:foreground ,aklk1ng-blue))))
   `(org-agenda-date-today ((t (:inherit org-agenda-date :underline t))))
   `(org-agenda-date-weekend ((t (:inherit org-agenda-date :foreground ,aklk1ng-fg+1))))
   `(org-agenda-date-weekend-today ((t (:inherit org-agenda-date-today :foreground ,aklk1ng-fg+1))))
   `(org-agenda-diary ((t (:inherit org-agenda-calendar-sexp))))
   `(org-agenda-dimmed-todo-face ((t (:inherit shadow))))
   `(org-agenda-done ((t (:foreground ,aklk1ng-fg-2))))
   `(org-agenda-filter-category ((t (:inherit bold :foreground ,aklk1ng-yellow))))
   `(org-agenda-filter-effort ((t (:inherit bold :foreground ,aklk1ng-yellow))))
   `(org-agenda-filter-regexp ((t (:inherit bold :foreground ,aklk1ng-yellow))))
   `(org-agenda-filter-tags ((t (:inherit bold :foreground ,aklk1ng-yellow))))
   `(org-agenda-restriction-lock ((t (:background ,aklk1ng-bg+1 :foreground ,aklk1ng-fg-1))))
   `(org-agenda-structure ((t (:inherit bold :foreground ,aklk1ng-fg+1))))
   `(org-agenda-structure-filter ((t (:inherit org-agenda-structure :foreground ,aklk1ng-orange))))
   `(org-agenda-structure-secondary ((t (:inherit font-lock-doc-face))))
   `(org-archived ((t (:background ,aklk1ng-bg+2 :foreground ,aklk1ng-fg))))
   `(org-block ((t (:background ,aklk1ng-bg-1 :extend t))))
   `(org-block-begin-line ((t (:inherit (shadow) :background ,aklk1ng-bg+1 :extend t))))
   `(org-block-end-line ((t (:inherit org-block-begin-line))))
   `(org-checkbox ((t (:foreground ,aklk1ng-orange))))
   `(org-checkbox-statistics-done ((t (:foreground ,aklk1ng-fg-1))))
   `(org-checkbox-statistics-todo ((t (:foreground ,aklk1ng-orange))))
   `(org-clock-overlay ((t (:background ,aklk1ng-bg+3))))
   `(org-code ((t (:foreground ,aklk1ng-fg+1))))
   `(org-column ((t (:background ,aklk1ng-bg+2))))
   `(org-column-title ((t (:inherit bold :background ,aklk1ng-bg+3 :foreground ,aklk1ng-fg+2))))
   `(org-date ((t (:foreground ,aklk1ng-blue :underline t))))
   `(org-date-selected ((t (:foreground ,aklk1ng-fg+2 :inverse-video t))))
   `(org-default ((t (:inherit default))))
   `(org-document-info ((t (:foreground ,aklk1ng-fg-1))))
   `(org-document-info-keyword ((t (:foreground ,aklk1ng-yellow))))
   `(org-document-title ((t (:inherit bold :foreground ,aklk1ng-blue :height 1.2))))
   `(org-done ((t (:foreground ,aklk1ng-fg-1))))
   `(org-drawer ((t (:foreground ,aklk1ng-yellow))))
   `(org-ellipsis ((t (:foreground ,aklk1ng-fg-1))))
   `(org-footnote ((t (:foreground ,aklk1ng-blue :underline t))))
   `(org-formula ((t (:foreground ,aklk1ng-orange))))
   `(org-headline-done ((t (:foreground ,aklk1ng-fg-1))))
   `(org-hide ((t (:foreground ,aklk1ng-bg))))
   `(org-latex-and-related ((t (:foreground ,aklk1ng-magenta))))
   `(org-level-1 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(org-level-2 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(org-level-3 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(org-level-4 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(org-level-5 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(org-level-6 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(org-level-7 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(org-level-8 ((t (:inherit bold :height unspecified :weight unspecified :foreground ,aklk1ng-blue))))
   `(org-link ((t (:foreground ,aklk1ng-blue :underline t))))
   `(org-list-dt ((t (:inherit bold))))
   `(org-macro ((t (:foreground ,aklk1ng-magenta))))
   `(org-meta-line ((t (:foreground ,aklk1ng-yellow))))
   `(org-mode-line-clock ((t (:inherit mode-line))))
   `(org-mode-line-clock-overrun ((t (:inherit mode-line :foreground ,aklk1ng-yellow))))
   `(org-priority ((t (:foreground ,aklk1ng-orange))))
   `(org-property-value ((t (:foreground ,aklk1ng-fg+1))))
   `(org-quote ((t (:inherit org-block))))
   `(org-scheduled ((t (:foreground ,aklk1ng-fg))))
   `(org-scheduled-previously ((t (:foreground ,aklk1ng-orange))))
   `(org-scheduled-today ((t (:foreground ,aklk1ng-fg+2))))
   `(org-sexp-date ((t (:foreground ,aklk1ng-blue))))
   `(org-special-keyword ((t (:foreground ,aklk1ng-yellow))))
   `(org-table ((t (:foreground ,aklk1ng-fg))))
   `(org-tag ((t (:foreground ,aklk1ng-yellow))))
   `(org-tag-group ((t (:inherit org-tag :weight bold))))
   `(org-target ((t (:foreground ,aklk1ng-blue))))
   `(org-time-grid ((t (:foreground ,aklk1ng-fg-1))))
   `(org-todo ((t (:foreground ,aklk1ng-orange))))
   `(org-upcoming-deadline ((t (:foreground ,aklk1ng-orange))))
   `(org-verbatim ((t (:foreground ,aklk1ng-fg+1))))
   `(org-verse ((t (:inherit org-block))))
   `(org-warning ((t (:inherit warning))))

   ;; ── Dired ──────────────────────────────────────────────
   `(dired-broken-symlink ((t (:inherit (error link)))))
   `(dired-directory ((t (:foreground ,aklk1ng-blue))))
   `(dired-flagged ((t (:background ,aklk1ng-error-bg))))
   `(dired-header ((t (:inherit bold))))
   `(dired-ignored ((t (:inherit shadow))))
   `(dired-mark ((t (:foreground ,aklk1ng-fg+2))))
   `(dired-marked ((t (:foreground ,aklk1ng-magenta))))
   `(dired-symlink ((t (:inherit link))))
   `(dired-warning ((t (:inherit warning))))
   `(dired-subtree-depth-1-face (nil))
   `(dired-subtree-depth-2-face (nil))
   `(dired-subtree-depth-3-face (nil))
   `(dired-subtree-depth-4-face (nil))
   `(dired-subtree-depth-5-face (nil))
   `(dired-subtree-depth-6-face (nil))
   `(diredfl-deletion ((t (:inherit dired-flagged))))
   `(diredfl-dir-name ((t (:inherit dired-directory))))
   `(diredfl-dir-priv ((t (:inherit dired-directory))))
   `(diredfl-flag-mark ((t (:inherit dired-marked))))
   `(diredfl-flag-mark-line ((t (:inherit dired-marked))))
   `(diredfl-symlink ((t (:inherit dired-symlink))))
   `(diredfl-tagged-autofile-name ((t (:inherit (diredfl-autofile-name dired-marked)))))

   ;; ── Image-Dired ────────────────────────────────────────
   `(image-dired-thumb-flagged ((t (:background ,aklk1ng-yellow))))
   `(image-dired-thumb-header-file-name ((t (:inherit bold))))
   `(image-dired-thumb-header-file-size ((t (:foreground ,aklk1ng-green))))
   `(image-dired-thumb-mark ((t (:background ,aklk1ng-green))))

   ;; ── Corfu ──────────────────────────
   `(corfu-current ((t (:background ,aklk1ng-bg+4))))
   `(corfu-bar ((t (:background ,aklk1ng-fg))))
   `(corfu-border ((t (:background ,aklk1ng-bg+3))))
   `(corfu-default ((t (:background ,aklk1ng-bg-1))))
   `(corfu-candidate-overlay-face ((t (:inherit shadow))))
   `(corfu-quick1 ((t (:inherit bold :background ,aklk1ng-error-bg))))
   `(corfu-quick2 ((t (:inherit bold :background ,aklk1ng-bg+2))))

   ;; ── Marginalia  ───────────────────
   `(marginalia-archive ((t (:foreground ,aklk1ng-blue))))
   `(marginalia-char ((t (:foreground ,aklk1ng-orange))))
   `(marginalia-date ((t (:foreground ,aklk1ng-fg+1))))
   `(marginalia-documentation ((t (:inherit italic :foreground ,aklk1ng-green))))
   `(marginalia-file-name (nil))
   `(marginalia-file-owner ((t (:inherit shadow))))
   `(marginalia-file-priv-dir (nil))
   `(marginalia-file-priv-exec ((t (:foreground ,aklk1ng-magenta))))
   `(marginalia-file-priv-link ((t (:foreground ,aklk1ng-blue))))
   `(marginalia-file-priv-no ((t (:inherit shadow))))
   `(marginalia-file-priv-other ((t (:foreground ,aklk1ng-blue))))
   `(marginalia-file-priv-rare ((t (:foreground ,aklk1ng-blue))))
   `(marginalia-file-priv-read ((t (:foreground ,aklk1ng-green))))
   `(marginalia-file-priv-write ((t (:foreground ,aklk1ng-orange))))
   `(marginalia-function ((t (:foreground ,aklk1ng-blue))))
   `(marginalia-key ((t (:foreground ,aklk1ng-yellow))))
   `(marginalia-lighter ((t (:inherit shadow))))
   `(marginalia-mode ((t (:foreground ,aklk1ng-magenta))))
   `(marginalia-modified ((t (:inherit warning))))
   `(marginalia-null ((t (:inherit shadow))))
   `(marginalia-number ((t (:foreground ,aklk1ng-magenta))))
   `(marginalia-size ((t (:foreground ,aklk1ng-blue))))
   `(marginalia-string ((t (:foreground ,aklk1ng-green))))
   `(marginalia-symbol ((t (:foreground ,aklk1ng-yellow))))
   `(marginalia-true (nil))
   `(marginalia-type ((t (:foreground ,aklk1ng-fg))))
   `(marginalia-value ((t (:inherit shadow))))
   `(marginalia-version ((t (:foreground ,aklk1ng-magenta))))

   ;; ── Vertico / Orderless ───────────────────────
   `(vertico-current ((t (:background ,aklk1ng-bg+4))))
   `(vertico-group-title ((t (:inherit bold :foreground ,aklk1ng-blue))))
   `(vertico-quick1 ((t (:inherit bold :background ,aklk1ng-error-bg))))
   `(vertico-quick2 ((t (:inherit bold :background ,aklk1ng-bg+2))))
   `(orderless-match-face-0 ((t (:inherit bold :foreground unspecified))))
   `(orderless-match-face-1 ((t (:inherit bold :foreground unspecified))))
   `(orderless-match-face-2 ((t (:inherit bold :foreground unspecified))))
   `(orderless-match-face-3 ((t (:inherit bold :foreground unspecified))))

   ;; ── Flycheck / Flymake / Diff-hl ───────────────────────
   `(flycheck-error ((t (:inherit aklk1ng-themes-underline-error))))
   `(flycheck-fringe-error ((t (:inherit aklk1ng-themes-mark-delete))))
   `(flycheck-fringe-info ((t (:inherit aklk1ng-themes-mark-select))))
   `(flycheck-fringe-warning ((t (:inherit aklk1ng-themes-mark-other))))
   `(flycheck-info ((t (:inherit aklk1ng-themes-underline-info))))
   `(flycheck-warning ((t (:inherit aklk1ng-themes-underline-warning))))
   `(flymake-error ((t (:inherit aklk1ng-themes-underline-error))))
   `(flymake-error-echo ((t (:inherit error))))
   `(flymake-note ((t (:inherit aklk1ng-themes-underline-info))))
   `(flymake-note-echo ((t (:inherit success))))
   `(flymake-warning ((t (:inherit aklk1ng-themes-underline-warning))))
   `(flymake-warning-echo ((t (:inherit warning))))
   `(diff-hl-change ((t (:background ,aklk1ng-diff-chg-bg+))))
   `(diff-hl-delete ((t (:background ,aklk1ng-diff-del-bg+))))
   `(diff-hl-insert ((t (:background ,aklk1ng-diff-add-bg+))))

   ;; ── Paren / Misc ───────────────────────
   `(show-paren-match ((t (:background ,aklk1ng-orange :foreground ,aklk1ng-fg+2))))
   `(show-paren-match-expression ((t (:background ,aklk1ng-bg+2))))
   `(show-paren-mismatch ((t (:background ,aklk1ng-red :foreground ,aklk1ng-fg+2))))

   `(eglot-mode-line ((t (:inherit bold :foreground ,aklk1ng-blue))))
   `(eglot-diagnostic-tag-unnecessary-face ((t (:inherit aklk1ng-themes-underline-info))))

   ;; ── Custom ─────────────────────────────────────────────
   `(custom-button ((t (:box (:color ,aklk1ng-border :style released-button)))))
   `(custom-button-mouse ((t (:inherit (highlight custom-button)))))
   `(custom-button-pressed ((t (:inherit (secondary-selection custom-button)))))
   `(custom-changed ((t (:background ,aklk1ng-diff-chg-bg))))
   `(custom-comment ((t (:inherit shadow))))
   `(custom-comment-tag ((t (:inherit (bold shadow)))))
   `(custom-face-tag ((t (:inherit bold :foreground ,aklk1ng-fg))))
   `(custom-group-tag ((t (:inherit bold :foreground ,aklk1ng-yellow))))
   `(custom-group-tag-1 ((t (:inherit bold :foreground ,aklk1ng-magenta))))
   `(custom-invalid ((t (:inherit error :strike-through t))))
   `(custom-modified ((t (:inherit custom-changed))))
   `(custom-rogue ((t (:inherit custom-invalid))))
   `(custom-set ((t (:inherit success))))
   `(custom-state ((t (:foreground ,aklk1ng-fg+1))))
   `(custom-themed ((t (:inherit custom-changed))))
   `(custom-variable-tag ((t (:inherit bold :foreground ,aklk1ng-blue))))
   `(custom-variable-obsolete ((t (:inherit shadow)))))

  ;; ── Variables ──────────────────────────────────────────
  (custom-theme-set-variables
   'aklk1ng
   '(frame-background-mode 'dark)))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'aklk1ng)
